<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_E-Konverter Hitungan Kurs_SourceNumber</name>
   <tag></tag>
   <elementGuidId>6531b202-70c7-43bb-9474-e35dd3d4c609</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='SourceNumber']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#SourceNumber</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9d85f017-9505-45c9-847c-33fb5be8924a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control txNumber numberPicker</value>
      <webElementGuid>ea6cac65-a05d-4b9a-9868-9828c73e0acc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SourceNumber</value>
      <webElementGuid>6405c821-b759-4181-b710-263e997ab767</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SourceNumber</value>
      <webElementGuid>143fbb5a-184d-4692-8415-9e923687b631</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f9b3631d-6c45-4def-881a-2ba4a879b697</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4a8d969b-8b3e-4721-ae6d-8e5ab878d7c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SourceNumber&quot;)</value>
      <webElementGuid>110c0895-d62b-42b3-95c5-b4bed1d1a9b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='SourceNumber']</value>
      <webElementGuid>18cd75c7-a472-41ef-9608-114af77f6607</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>cd4ee22b-94c8-484b-a1e9-6a5695732deb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'SourceNumber' and @name = 'SourceNumber' and @type = 'text']</value>
      <webElementGuid>b88b256a-2f4d-4627-a657-8ca435af9a49</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
