<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_USDJPYGBPAUDHKDSGDEURIDRMYRSARCNY</name>
   <tag></tag>
   <elementGuidId>a06984ef-40fa-4dc3-be57-1c507fd03cbb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//select[@id='CurrencyCode'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>2e5f293f-1b23-466f-8737-d797c68093fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control cbCurrencyTo</value>
      <webElementGuid>666fabbb-a9d6-4f99-94eb-b93aad93118a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CurrencyCode</value>
      <webElementGuid>0602710a-1084-4536-a401-b8d365e1878a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CurrencyCode</value>
      <webElementGuid>c4eb17e3-d97f-4d8f-bdda-5685cfdd8e74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>USD
JPY
GBP
AUD
HKD
SGD
EUR
IDR
MYR
SAR
CNY
</value>
      <webElementGuid>186cb27e-d26d-4f4d-bf09-5577993008b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;btn-wrapper&quot;]/div[@class=&quot;btn-content&quot;]/section[@class=&quot;section-area mb-40&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-7&quot;]/div[@class=&quot;converter-box converter-box__wrapper&quot;]/div[@class=&quot;converter-box__content&quot;]/form[@class=&quot;form-converter&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-3&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;select-wrapper select-kurs1&quot;]/select[@id=&quot;CurrencyCode&quot;]</value>
      <webElementGuid>317598ba-ffe2-4db3-9206-f205d5316bbe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//select[@id='CurrencyCode'])[2]</value>
      <webElementGuid>5f53bee9-b63c-4a49-a3f4-08ace29bcb66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transaksi'])[1]/following::select[2]</value>
      <webElementGuid>4009b6de-b8bb-4d36-9562-8caa5bf73a18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='E-Konverter Hitungan Kurs'])[2]/following::select[3]</value>
      <webElementGuid>5f4fee9b-1a84-4009-a542-7690317ae80f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='USD'])[7]/preceding::select[1]</value>
      <webElementGuid>fd75e5c5-3dd6-4baa-90ad-beaa563bf764</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JPY'])[6]/preceding::select[1]</value>
      <webElementGuid>56f9979c-e137-4129-bbd5-8e6a8593fd91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/select</value>
      <webElementGuid>2f470b9c-09f5-48da-b2ca-433a23228e33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'CurrencyCode' and @name = 'CurrencyCode' and (text() = 'USD
JPY
GBP
AUD
HKD
SGD
EUR
IDR
MYR
SAR
CNY
' or . = 'USD
JPY
GBP
AUD
HKD
SGD
EUR
IDR
MYR
SAR
CNY
')]</value>
      <webElementGuid>fc30724b-6da3-4820-b105-6900da430585</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
