<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Element_1697447974547</name>
   <tag></tag>
   <elementGuidId>be22277e-06bd-4f2e-a670-4d8319d75d5f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>0adb4145-89b2-4085-a794-e4ab4c219bf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1697447974547</value>
      <webElementGuid>ecce3e89-896f-4deb-90ae-18b18d822f9f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
