<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Element_1697447897284</name>
   <tag></tag>
   <elementGuidId>66b14050-b77c-458a-918f-5819946c7b9a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>bdbae4a9-f334-4858-acc4-d03e301ed238</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1697447897284</value>
      <webElementGuid>175100fc-b537-4c94-b7af-1d196bc1cf16</webElementGuid>
   </webElementProperties>
</WebElementEntity>
