<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mata uang</name>
   <tag></tag>
   <elementGuidId>8761aa4e-2612-46a4-a11c-0284cae45e26</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>1a2caac9-151f-49fb-a515-bd8510cc8317</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1697447878324</value>
      <webElementGuid>9e36524c-d3b7-46d0-962d-a1b01500a82b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
