<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>nominal 10</name>
   <tag></tag>
   <elementGuidId>943286f7-7ef2-468a-a2b5-4b0dacfc9a47</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>!</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>583140ab-7213-4cde-b345-0e44bd7c742b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1697447847708</value>
      <webElementGuid>bb5961bc-40c7-42c7-a4ea-a2d116e23691</webElementGuid>
   </webElementProperties>
</WebElementEntity>
