<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_E-Konverter Hitungan Kurs_SourceNumber</name>
   <tag></tag>
   <elementGuidId>4233cce1-e8c1-4945-92b2-b501ddeb0648</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='SourceNumber']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#SourceNumber</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ba78a3ad-21d5-4d1a-a116-3b502bb9d6c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control txNumber numberPicker</value>
      <webElementGuid>861bbd8c-86d8-40c1-a213-d383e3429097</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SourceNumber</value>
      <webElementGuid>97376f69-bdfe-4a3f-8cdf-1cdc69578c83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SourceNumber</value>
      <webElementGuid>275c177e-0f29-482c-8fe5-646c7c138589</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>555d2ae3-ba16-4242-9560-2c103317a643</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d5277b53-14f0-4eca-a053-ed8933eefd69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SourceNumber&quot;)</value>
      <webElementGuid>4daa2f26-db79-4658-97fb-759073f5b36d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='SourceNumber']</value>
      <webElementGuid>4e043512-56a8-42dd-83b0-5cc50e0d25bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>66dc9453-f86e-44e4-a6b6-a3318b91aff0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'SourceNumber' and @name = 'SourceNumber' and @type = 'text']</value>
      <webElementGuid>8daff419-2b36-42e2-98e0-170b5f5e3923</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
